# Generated by Django 5.0.6 on 2024-06-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('medicine_registration_number', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('manufacture_date', models.DateField()),
                ('shelf_life_days', models.IntegerField()),
                ('medicine_group', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prescription_required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_code', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(max_length=255)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('supply_code', models.IntegerField(primary_key=True, serialize=False)),
                ('supply_date', models.DateField()),
                ('medicine_registration_number', models.IntegerField()),
                ('quantity_supplied', models.IntegerField()),
                ('supplier_code', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab8DataBase.medicines')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab8DataBase.suppliers')),
            ],
        ),
    ]
